apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext2
  labels:
    app: BoundedContext2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext2
  template:
    metadata:
      labels:
        app: BoundedContext2
    spec:
      containers:
        - name: BoundedContext2
          image: username/BoundedContext2:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5